service: demo-sls
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
functions:
  api:
    handler: src/api/api.handler
    events:
      - httpApi:
          path: /api
          method: GET
  todos:
    handler: src/api/todos.handler
    events:
      - httpApi:
          path: /todo
          method: GET
  todo:
    handler: src/api/todo.handler
    events:
      - httpApi:
          path: /todo/{id}
          method: GET
          request:
            parameters:
              id: true
plugins:
  - serverless-offline